// AUTO-GENERATED by scripts/convert-sample-data.mjs — do not edit by hand.
// Source: sample-data/raw/<locale>.json (real pipeline output, persona "Max Beispiel").
import type { PdfUserProfile } from "@/lib/pdf/generateReport";
import type { HeroSummary } from "@/lib/reports/hero-summary";
import type { DataInsights } from "@/lib/reports/data-insights";
import type { ScoreDataBasis } from "@/lib/reports/score-data-basis";

interface SampleScoresDisplay {
  activity: { activity_score_0_100: number; total_met_minutes_week: number; activity_category: string };
  sleep: { sleep_score_0_100: number; sleep_band: string; sleep_duration_band: string; sleep_duration_score: number; sleep_quality_score: number; wakeup_score: number; recovery_score: number };
  vo2max: { fitness_score_0_100: number; vo2max_estimated: number; vo2max_band: string };
  metabolic: { metabolic_score_0_100: number; metabolic_band: string; bmi: number; bmi_category: string };
  stress: { stress_score_0_100: number; stress_band: string };
  overall_score_0_100: number;
  overall_band: string;
}

const SCORES_DISPLAY: Record<string, SampleScoresDisplay> = {
  de: {
  "activity": {
    "activity_score_0_100": 43,
    "total_met_minutes_week": 813,
    "activity_category": "MODERATE"
  },
  "sleep": {
    "sleep_score_0_100": 60,
    "sleep_band": "moderate",
    "sleep_duration_band": "kurz",
    "sleep_duration_score": 55,
    "sleep_quality_score": 80,
    "wakeup_score": 38,
    "recovery_score": 50
  },
  "vo2max": {
    "fitness_score_0_100": 50,
    "vo2max_estimated": 36.1,
    "vo2max_band": "Fair"
  },
  "metabolic": {
    "metabolic_score_0_100": 57,
    "metabolic_band": "moderate",
    "bmi": 26.3,
    "bmi_category": "overweight"
  },
  "stress": {
    "stress_score_0_100": 30,
    "stress_band": "high"
  },
  "overall_score_0_100": 50,
  "overall_band": "moderate"
},
};

const HERO: Record<string, HeroSummary> = {
  de: {
  "total_datapoints": 49,
  "sources": [
    {
      "type": "whoop",
      "icon": "🔥",
      "label": "7 Tage WHOOP Tracking"
    }
  ],
  "has_any_data": true,
  "quality_level": "good",
  "period_start": "14. Mai 2026",
  "period_end": "20. Mai 2026"
},
};

const INSIGHTS: Record<string, DataInsights> = {
  de: {
  "sleep": [
    {
      "label_key": "duration",
      "value": "6.6",
      "unit": "h",
      "evaluation": {
        "status": "borderline",
        "reference": "NSF: 7–9h",
        "color": "#F59E0B"
      }
    },
    {
      "label_key": "efficiency",
      "value": "88",
      "unit": "%",
      "evaluation": {
        "status": "optimal",
        "reference": "AASM: ≥85%",
        "color": "#22C55E"
      }
    },
    {
      "label_key": "deep_sleep",
      "value": "50",
      "unit": "min",
      "evaluation": {
        "status": "borderline",
        "reference": "AASM: 60–110 min",
        "color": "#F59E0B"
      }
    },
    {
      "label_key": "rem",
      "value": "52",
      "unit": "min",
      "evaluation": {
        "status": "borderline",
        "reference": "AASM: 90–120 min",
        "color": "#F59E0B"
      }
    }
  ],
  "activity": [
    {
      "label_key": "strain",
      "value": "8.2",
      "unit": "/ 21",
      "evaluation": {
        "status": "low",
        "reference": "WHOOP: <10",
        "color": "#E63222"
      }
    }
  ],
  "vo2max": [
    {
      "label_key": "value",
      "value": "36.1",
      "unit": "ml/kg/min",
      "evaluation": {
        "status": "low",
        "reference": "ACSM: <38",
        "color": "#E63222"
      }
    }
  ],
  "metabolic": [
    {
      "label_key": "bmi",
      "value": "26.3",
      "unit": "kg/m²",
      "evaluation": {
        "status": "borderline",
        "reference": "WHO: 18.5–24.9",
        "color": "#F59E0B"
      }
    }
  ],
  "stress": [
    {
      "label_key": "hrv",
      "value": "40",
      "unit": "ms",
      "evaluation": {
        "status": "borderline",
        "reference": "Norm: ≥25 ms",
        "color": "#F59E0B"
      }
    },
    {
      "label_key": "rhr",
      "value": "66",
      "unit": "bpm",
      "evaluation": {
        "status": "good",
        "reference": "AHA: 60–72 bpm",
        "color": "#22C55E"
      }
    },
    {
      "label_key": "whoop_recovery",
      "value": "54",
      "unit": "%",
      "evaluation": {
        "status": "good",
        "reference": "WHOOP: 34–66%",
        "color": "#22C55E"
      }
    }
  ]
},
};

const BASIS: Record<string, Record<string, ScoreDataBasis>> = {
  de: {
  "activity": {
    "icon": "🔥",
    "label": "7T WHOOP",
    "type": "positive"
  },
  "sleep": {
    "icon": "🔥",
    "label": "7T WHOOP",
    "type": "positive"
  },
  "vo2max": {
    "icon": "📋",
    "label": "Geschätzt aus Angaben",
    "type": "neutral"
  },
  "metabolic": {
    "icon": "📋",
    "label": "Fragebogen",
    "type": "muted"
  },
  "stress": {
    "icon": "🔥",
    "label": "7T HRV-Tracking",
    "type": "positive"
  }
},
};

const INTERPRETATIONS: Record<string, Record<string, string>> = {
  de: {
  "sleep": "Deine Schlafdauer von 6,5 h und die häufigen Aufwacher drücken deinen Schlaf-Score auf 60/100. Bei einem ohnehin niedrigen Stress-Score von 30/100 deutet das auf eine erhöhte Erholungsbelastung hin. Die morgendliche Erholung von 5/10 spiegelt sich direkt in deinem schwachen Aktivitäts-Score von 43/100 wider.",
  "activity": "Mit 9 Stunden Sitzen täglich und 0 erfassten Schritten fällt dein Aktivitätsscore auf 43/100. Trotz moderater MET-Minuten (813/Woche) verstärkt das hohe Sitzen deinen Stresswert von nur 30/100 zusätzlich. Die Diskrepanz zeigt, dass sporadische Belastung langes Sitzen nicht ausgleicht.",
  "vo2max": "Dein VO2max liegt bei 36,1 ml/kg/min – das entspricht einem „Fair\"-Niveau und deutet auf eine begrenzte aerobe Kapazität hin. Kombiniert mit deinem niedrigen Aktivitätsscore von 43/100 zeigt sich, dass dein Körper aktuell wenig kardiovaskuläre Reize bekommt. Der hohe Stresswert (30/100) könnte die Erholung zusätzlich belasten.",
  "metabolic": "Dein BMI liegt mit 26,3 kg/m² im übergewichtigen Bereich, begleitet von nur 1,75 L Wasseraufnahme täglich. In Kombination mit deinem niedrigen Aktivitätsscore (43/100) verstärkt sich der metabolische Druck spürbar. Der hohe Stresswert (30/100) dürfte die Stoffwechselregulation zusätzlich belasten.",
  "stress": "Dein Stresswert liegt bei nur 30/100, und du berichtest subjektiv 7 von 10 Stresslevel – ein deutliches Warnsignal. Kombiniert mit einem Schlafwert von 60/100 deutet das auf eine erhöhte Gesamtbelastung hin. Beide Puffer liegen bei 0, was zeigt, dass aktuell keine Reserve vorhanden ist."
},
};

export const SAMPLE_PDF_USER: PdfUserProfile = {
  "email": "max.beispiel@boostthebeast.com",
  "age": 35,
  "gender": "male",
  "bmi": 26.3,
  "bmi_category": "overweight",
  "body_type": "male_2"
};

export function getSampleScoresDisplay(locale: string): SampleScoresDisplay {
  return SCORES_DISPLAY[locale] ?? SCORES_DISPLAY.de;
}
export function getSampleHeroSummary(locale: string): HeroSummary {
  return HERO[locale] ?? HERO.de;
}
export function getSampleDataInsights(locale: string): DataInsights {
  return INSIGHTS[locale] ?? INSIGHTS.de;
}
export function getSampleScoreDataBasis(locale: string): Record<string, ScoreDataBasis> {
  return BASIS[locale] ?? BASIS.de;
}
export function getSampleInterpretations(locale: string): Record<string, string> {
  return INTERPRETATIONS[locale] ?? INTERPRETATIONS.de;
}
