// AUTO-GENERATED by scripts/convert-sample-data.mjs — do not edit by hand.
// Source: sample-data/raw/<locale>.json (real /api/report/generate output).
import type { PdfReportContent, PdfScores } from "@/lib/pdf/generateReport";

const CONTENT: Record<string, PdfReportContent> = {
  de: {
  "headline": "Recovery-Score 38/100 bei gleichzeitig 9h Sitzzeit täglich — dein System ist unter Dauerlast, obwohl du kaum formell trainierst.",
  "executive_summary": "Dein Overall Performance Index von 50/100 ist das Resultat eines Systems, das an mehreren Stellen gleichzeitig unter Druck steht — nicht durch Übertraining, sondern durch strukturelle Alltagsbelastung. Der stärkste Hebel ist dein Stress-Score von 30/100: ein Stresslevel von 7/10, kombiniert mit Job- und Familienbelastung, deckelт aktiv sowohl deine Schlafqualität als auch deine Recovery-Kapazität. Dein über 7 Tage gemessener Recovery-Score von 38/100 ist dabei kein Trainingsschaden — du trainierst aktuell 0 Einheiten pro Woche — sondern ein Signal, dass dein Erholungs-Fundament ohne zusätzliche Trainingsreize bereits an seiner Kapazitätsgrenze operiert. Deine gemessene Schlafdauer von 6.5h ist kurz für vollständige Regeneration: die fragmentierte Schlafstruktur (häufiges Aufwachen) begrenzt die kumulative Wachstumshormon-Ausschüttung, was direkt in den Recovery-Score einfließt. Gleichzeitig sitzt du 9 Stunden täglich — eine Schwelle, ab der die Forschung unabhängige kardiometabolische Risiken dokumentiert, die kein Trainingspensum vollständig kompensiert. Dein Metabolic Score von 57/100 und dein BMI von 26.3 passen zu deiner Selbsteinschätzung als männlicher Typ 2 und zeigen: das Ziel Körperkomposition verbessern ist realistisch, aber es beginnt nicht im Gym — es beginnt bei Schlaf, Stress und Sitzzeit. Ohne diese Basis wird jedes Trainingsprogramm gegen einen Recovery-Score von 38 anlaufen und kaum Adaption produzieren.",
  "critical_flag": "Sitzzeit von 9h/Tag liegt im kritischen Bereich — unabhängiger CVD-Risikofaktor laut AHA Science Advisory, nicht kompensierbar durch die aktuell 0 Trainingseinheiten/Woche. Sofortige Unterbrechungsroutine erforderlich.",
  "modules": {
    "sleep": {
      "score_context": "Dein Sleep Score von 60/100 bedeutet: du schläfst gerade genug, um funktionsfähig zu bleiben — aber nicht genug, um metabolische Stabilität und vollständige neuronale Regeneration zu gewährleisten. Du gibst an, dich morgens mit 5 von 10 erholt zu fühlen, und deine über 7 Tage gemessenen WHOOP-Daten bestätigen das: 6.5h Schlafdauer bei häufigem nächtlichem Aufwachen ist eine Kombination, die den Tiefschlafanteil (N3) zwar erreicht, aber fragmentiert. Der Alltag läuft — aber dein Körper zahlt einen laufenden Erholungskredit.",
      "key_finding": "Grenzwertige Schlafdauer zwischen 6 und 7 Stunden ist in Meta-Analysen mit erhöhter Insulinresistenz und erhöhtem Übergewichtsrisiko assoziiert — unabhängig von der Ernährung. Kaczmarek et al. (2025) zeigen direkt, dass Schlafmangel Cortisol erhöht, Testosteron senkt und Wachstumshormon-Ausschüttung limitiert — alles drei sind Parameter, die du für dein Ziel Körperkomposition verbessern brauchst. Dein Sleep Multiplier von ×0.82 zieht deinen Recovery-Score messbar nach unten: ohne diesen Abzug wäre deine Basis-Recovery 54/100 — mit ihm landest du bei 38/100.",
      "systemic_connection": "Schlechter Schlaf ist kein isoliertes Problem — er ist der Multiplikator, der alle anderen Scores begrenzt. Dein Stress-Score von 30/100 verschlechtert die Schlafqualität durch erhöhte abendliche Kortisol-Spiegel, und dein Schlaf liefert im Gegenzug keine ausreichende Cortisol-Suppression — ein sich selbst verstärkender Kreislauf. Concreet: Covassin et al. (2022) zeigen in einem RCT, dass Schlafmangel zu mehr viszeralem Bauchfett führt — unabhängig von der Ernährung — was direkt gegen dein Kompositions-Ziel arbeitet.",
      "limitation": "Das schwächste Glied in deinem Schlaf ist nicht die Einschlafzeit, sondern die Durchschlaf-Kontinuität: häufiges nächtliches Aufwachen verhindert ausreichend lange N3- und REM-Phasen, auch wenn die Gesamtdauer knapp ausreicht. Solange dieser Faktor nicht adressiert wird, bleibt der Sleep Multiplier bei ~0.82 und deckelst damit systematisch deinen Recovery-Score — unabhängig davon, wie diszipliniert dein Training ist.",
      "recommendation": "Priorisiere zuerst die Schlaf-Kontinuität, dann die Dauer. Konkret: Bildschirm-Cutoff 60 Minuten vor dem Einschlafen (Blaulicht erhöht Cortisol-Spiegel abends messbar), Schlafzimmer-Temperatur auf 16–19°C (thermoregulatorisches Signal für tiefere Schlafphasen), und eine feste Aufwachzeit 7 Tage die Woche — auch am Wochenende. Das Ziel sind 7.5h mit weniger Unterbrechungen; wenn du das 4 Wochen konsequent hältst, wird dein Sleep Multiplier von ×0.82 in Richtung ×0.90+ wandern, was deinen Recovery-Score messbar hebt — ohne eine einzige Trainingsminute mehr."
    },
    "recovery": {
      "score_context": "Dein über 7 Tage gemessener Recovery-Score von 38/100 ist in einem Kontext zu lesen, den viele Menschen übersehen: du trainierst aktuell 0 Einheiten pro Woche — und trotzdem liegt deine Erholung im Low-Band. Das bedeutet, dein Alltagsleben allein — 9h Sitzen, 7/10 Stresslevel, 6.5h fragmentierter Schlaf — produziert bereits eine Erholungsschuld, die dein System täglich abarbeiten muss. Du hast noch keine Trainingsreize hinzugefügt, und dein System ist bereits knapp.",
      "key_finding": "Die beiden Multiplikatoren, die deinen Recovery-Score von der Basis 54/100 auf 38/100 ziehen, sind Sleep (×0.82) und Stress (×0.87). Das ist kein Zufall — beide wirken über denselben Mechanismus: chronisch erhöhtes Cortisol durch Schlafmangel und psychosoziale Belastung hemmt die anabole Achse (Testosteron, Wachstumshormon), die für Gewebereparatur und Muskelregeneration verantwortlich ist. PMC Chronic Stress & Cognition (2024) dokumentiert zusätzlich, dass anhaltende Glucocorticoid-Ausschüttung präfrontale Funktionen beeinträchtigt — was erklärt, warum du dich bei 5/10 Erholungsgefühl nicht nur körperlich, sondern auch mental nicht frisch fühlst.",
      "systemic_connection": "Ein Recovery-Score von 38/100 ist die direkte Obergrenze für Trainingsadaption: wenn du jetzt 3× pro Woche strukturiertes Training einführst, ohne Schlaf und Stress zu adressieren, wird dein Körper auf diese Reize kaum adaptieren — die Regenerationskapazität ist nicht vorhanden. PMC OTS Review (2025) und ScienceDirect OTS Molecular (2025) zeigen, dass unzureichende Recovery Kraftverluste bis zu 14% und erhöhte Verletzungsanfälligkeit produziert — selbst ohne Overtraining im klassischen Sinn.",
      "overtraining_signal": "Kein Overtraining-Signal aktiv — du trainierst 0 Einheiten pro Woche. Der niedrige Recovery-Score ist rein alltagsinduziert (Stress + Schlaf). Das ist relevant: es bedeutet, dass du Spielraum hast, moderates Training einzuführen, ohne das System weiter zu belasten — aber nur, wenn du gleichzeitig die Recovery-Basis verstärkst.",
      "limitation": "Deine Erholungs-Umgebung ist die Limitierung — nicht dein Training. Solange dein Stress-Multiplier bei ×0.87 und dein Sleep-Multiplier bei ×0.82 bleiben, ist der Recovery-Score strukturell gedeckelt bei etwa 38–45/100. Kein Trainingsprogramm, keine Supplementation und keine Diät durchbricht diese Decke nachhaltig.",
      "recommendation": "Beginne mit einem Einheiten pro Woche Einstieg (eine moderate 30-minütige Einheit, kein HIIT, kein Maximalkraft) — aber parallelisiere das mit einer Schlaf-Routine-Intervention und einer täglichen Stress-Downregulation von 10 Minuten. Nach 4 Wochen: wenn dein Erholungsgefühl morgens auf 6–7/10 steigt, kannst du auf 2 Einheiten pro Woche erhöhen. Der Recovery-Score ist dein primäres grünes Licht für Trainingsvolumen-Erhöhung — nicht der Kalender."
    },
    "activity": {
      "score_context": "Dein Activity Score von 43/100 im moderaten Band spiegelt wider, dass du dich bewegst — aber in einer Zusammensetzung, die für dein Ziel Körperkomposition und VO2max-Steigerung suboptimal ist. Deine 813 MET-Minuten pro Woche teilen sich auf in 413 MET-Minuten Walking und 400 MET-Minuten moderate Aktivität — ohne eine einzige Minute intensive Aktivität (Vigorous MET: 0). Du erreichst die WHO-Mindestempfehlung von 150 Minuten moderate Aktivität, aber du bewege dich im unteren Bereich der Kurve, wo weitere Intensität noch den stärksten marginalen Gesundheitsgewinn bringt.",
      "key_finding": "Die AHA Circulation-Studie (2022, über 100.000 Teilnehmer, 30 Jahre Beobachtungszeitraum) zeigt: 150–300 Minuten moderate Aktivität pro Woche entsprechen ~20–21% niedrigerem Mortalitätsrisiko. Du bist in dieser Zone. Die AMA Longevity-Analyse (2024) ergänzt: 150–299 Minuten intensive Aktivität pro Woche wären mit 21–23% Reduktion Gesamtmortalität und 27–33% Reduktion CVD-Mortalität verbunden. Der Schritt von 0 auf auch nur 1 intensive Einheit pro Woche wäre der effektivste Einzelhebel für deine Langzeitgesundheit — und würde gleichzeitig deinen geschätzten VO2max von 36.1 ml/kg/min steigern.",
      "met_context": "Deine 813 MET-Minuten pro Woche liegen im IPAQ-Moderate-Bereich. Zum Vergleich: die IPAQ-Kategorie 'High' beginnt bei 3.000 MET-Minuten/Woche — du bist bei etwa 27% davon. Für dein Ziel Körperkomposition ist nicht nur das Volumen relevant, sondern die Intensitätsverteilung: 0 Minuten Vigorous-Aktivität bedeutet kaum Nachverbrennungseffekt (EPOC) und begrenzte Muskelstimulation.",
      "systemic_connection": "Deine Aktivität beeinflusst direkt deinen Metabolic Score (57/100) und deine geschätzte VO2max (36.1 ml/kg/min). Mehr Intensität — nicht mehr Volumen — wäre der kürzeste Weg zu beiden. Gleichzeitig ist deine Sitzzeit von 9h/Tag ein eigenständiges Problem: Frontiers (2022) dokumentiert bei >6h Sitzen erhöhtes Risiko für 12 chronische Erkrankungen, und die AHA Science Advisory zeigt, dass Sitzzeit das Metabolisches-Syndrom-Odds um Faktor 1.73 erhöht — auch nach Adjustierung für Bewegungszeit. Du trainierst also (moderat), sitzt aber trotzdem 9 Stunden täglich, was einen unabhängigen Risikopfad offen lässt.",
      "sitting_flag": "Deine Sitzzeit von 9 Stunden täglich ist eine aktive systemische Warnung. Die AHA Science Advisory klassifiziert Sitzzeit als unabhängigen CVD-Risikofaktor — das bedeutet: selbst wenn du 3× pro Woche trainierst, bleibt das Sitzzeit-Risiko bestehen, wenn du den Rest des Tages 9 Stunden sitzt. Frontiers (2022) verknüpft diese Schwelle mit erhöhtem Risiko für 12 chronische Erkrankungen einschließlich Typ-2-Diabetes, CVD und metabolischem Syndrom. Der einzige Hebel: Sitz-Blöcke spätestens alle 45–60 Minuten durch 2–3 Minuten aktive Bewegung unterbrechen — nicht 'aufstehen', sondern tatsächlich gehen.",
      "limitation": "Du hast aktuell 0 strukturierte Trainingseinheiten pro Woche und 3 Stunden täglich auf den Beinen — das reicht nicht, um Muskelmasse aufzubauen oder die Körperkomposition relevant zu verschieben, selbst bei guter Ernährung. Die Kombination aus 0 Widerstandstraining und 9h Sitzen produziert aktiv Muskelmasse-Verlust über Zeit (sarkopenes Potenzial).",
      "recommendation": "Starte mit einer Trainingseinheit pro Woche in den ersten 4 Wochen — fokussiert auf Ganzkörper-Widerstandstraining (30–40 Minuten, 3–4 Übungen Compound-Muster: Kniebeugen, Rudern, Drücken, Hüftstreckung). Woche 5–8: auf 2 Einheiten erhöhen. Ab Woche 9, wenn Recovery-Score auf >50 gestiegen ist: eine dritte Einheit als moderate Intensitäts-Session ergänzen. Parallel dazu: Sitz-Pausen alle 45 Minuten als nicht-verhandelbare Alltagsroutine — das ist der Hebel, der unabhängig vom Training wirkt."
    },
    "metabolic": {
      "score_context": "Dein Metabolic Score von 57/100 zeigt ein System ohne akute Risikomarker, aber mit mehreren Faktoren, die den Score strukturell unter 70 halten. Du gibst an, 3 Mahlzeiten täglich zu essen, 1.75 Liter Wasser zu trinken und Obst und Gemüse nur eher selten zu konsumieren (3–7 Mal pro Woche) — das sind alles adjustierbare Variablen, keine fixen Limits. Das Potenzial für einen höheren Score liegt klar vor dir.",
      "key_finding": "Zwei Faktoren ziehen deinen Metabolic Score am stärksten: deine Sitzzeit von 9h/Tag und dein BMI von 26.3 kg/m². Deine Selbsteinschätzung als männlicher Typ 2 (schlanker Körperbau) und dein BMI von 26.3 stimmen überein — der BMI reflektiert hier tatsächlich einen erhöhten Körperfettanteil, nicht Muskelmasse. Das ist kein Urteil, sondern dein aktueller Ausgangspunkt für das Ziel Körperkomposition verbessern. Die JAMA Network Open Meta-Analyse (2024, 29 RCTs) zeigt, dass zeitlich eingeschränktes Essen und frühe Kalorienverteilung zu signifikant größerem Gewichtsverlust führen — ein Hebel, der ohne zusätzliche Zeit auskommt.",
      "bmi_context": "Dein BMI von 26.3 kg/m² liegt laut WHO im Übergewichts-Bereich. Deine Selbsteinschätzung als männlicher Körpertyp 2 bestätigt, dass dieser Wert den aktuellen Körperfettanteil widerspiegelt und nicht durch überdurchschnittliche Muskelmasse erklärt wird. Das ist der Ausgangspunkt für dein Ziel — keine Grundlage für Beschämung, sondern eine messbare Variable, die du über Ernährungskomposition, Schlaf und moderates Widerstandstraining direkt beeinflussen kannst. BMI ist als Populations-Schätzer einzuordnen; eine Körperfett-Messung (z.B. DEXA oder Caliper) würde dir präzisere Daten liefern.",
      "systemic_connection": "Dein Metabolic Score ist direkt an Schlaf und Stress gekoppelt — nicht nur durch Ernährung. Covassin et al. (2022) zeigen: Schlafmangel erhöht viszerales Bauchfett unabhängig von der Kalorienzufuhr. Sondrup et al. (2022) dokumentieren, dass Schlafmangel Insulinresistenz signifikant erhöht. Das bedeutet konkret: Wenn du deinen Schlaf von 6.5h auf 7.5h verbesserst, verbesserst du damit direkt deinen Metabolic Score — ohne Diät, ohne Training.",
      "limitation": "Dein Obst- und Gemüsekonsum von 3–7 Mahlzeiten pro Woche und dein Wasserkonsum von 1.75 Litern täglich sind die zwei einfachsten und zeiteffizientesten Hebel im Metabolic-Modul. Beides ist kein strukturelles Problem — du gibst an, keine Zeit zu haben (no_time) — sondern eine Frage von Systemgestaltung, nicht Willenskraft.",
      "recommendation": "Drei Mahlzeiten täglich ist eine gute Basis — optimiere das Timing: frühstücke innerhalb von 60 Minuten nach dem Aufwachen (stabilisiert die morgendliche Cortisol-Kurve), verlagere mehr Kalorien auf die erste Tageshälfte (JAMA-Evidenz: frühe Kalorienverteilung begünstigt Fettabbau), und beende die letzte Mahlzeit 2–3 Stunden vor dem Schlafen. Erhöhe den Proteinanteil pro Mahlzeit auf mindestens 25–30g — das reduziert abendliche Cravings messbar (Sättigungshormon-Mechanismus). Wasser: 2.5 Liter täglich als Ziel; ein Glas Wasser beim Aufstehen und eines vor jeder Mahlzeit kostet null Minuten und deckt den Gap."
    },
    "stress": {
      "score_context": "Dein Stress Score von 30/100 ist das schwächste Modul in deinem Profil und hat die meisten Verbindungen zu anderen Scores. Du gibst einen Stresslevel von 7 von 10 an, mit Job und Familie als Hauptquellen. Das ist kein Soft-Faktor — das ist ein physiologisches Signal: bei chronisch erhöhtem Cortisol durch Allostatic Load läuft dein Hormonprofil täglich gegen Regeneration, Körperkomposition und kognitive Performance.",
      "key_finding": "Das Allostatic Load Modell beschreibt genau deinen Zustand: dein Körper zahlt laufend die metabolischen und hormonellen Kosten der Anpassung an anhaltenden Stress. Bei einem Stresslevel von 7/10 über Wochen beginnen die sekundären Effekte messbar zu werden — Schlafqualität leidet (dein Stress-Multiplier liegt bei ×0.87), Testosteron-Regeneration wird gebremst, und viszerale Fetteinlagerung wird begünstigt. Die Psychoneuroendocrinology Meta-Analyse (2024) zeigt, dass Mindfulness (Effektgröße g=0.345) und strukturierte Entspannungsverfahren (g=0.347) die am besten belegten Maßnahmen zur Cortisol-Senkung sind — mit einem Effekt, der nach 4–8 Wochen messbar wird.",
      "hpa_context": "Kein formales HPA-Achsen-Risiko aktiv laut Input. Dein Stresslevel von 7/10 ist jedoch ein Signal, das ernst zu nehmen ist: Die PMC Chronic Stress & Cognition-Studie (2024) zeigt, dass anhaltend erhöhte Glucocorticoid-Ausschüttung — auch unterhalb der klinischen Schwelle — präfrontale Kortex- und Hippocampus-Funktionen beeinträchtigt. Das erklärt, warum du bei diesem Stressprofil vermutlich nicht auf dem kognitiven Niveau operierst, das dir möglich wäre.",
      "systemic_connection": "Dein Stresslevel von 7/10 ist der Faktor, der simultán Schlaf (×0.87 Multiplier), Recovery (Testosteron- und Wachstumshormon-Suppression) und Metabolic (viszerale Fetteinlagerung, Insulinresistenz) nach unten zieht. Er ist auch die einzige Variable, bei der eine Verbesserung direkt und sofort auf drei andere Module wirkt. Die Empfehlung der Top-Priorität basiert genau darauf.",
      "limitation": "Dein Recovery-Ritual ist Sport — aber du trainierst aktuell 0 Einheiten pro Woche. Das bedeutet, der primäre Stress-Puffer, den du selbst als effektiv kennst, ist gerade nicht aktiv. Dieser Gap zwischen bevorzugter Erholungsstrategie und tatsächlichem Verhalten erklärt einen Teil der Stressakkumulation.",
      "recommendation": "Zwei Hebel parallel aktivieren, die in der Psychoneuroendocrinology Meta-Analyse (2024) die stärkste Cortisol-senkende Wirkung zeigen: (1) Tägliche 10-minütige Box-Breathing-Routine (4 Sekunden ein, 4 Sekunden halten, 4 Sekunden aus, 4 Sekunden halten — 2× täglich, am effektivsten direkt nach dem letzten Arbeitstermin des Tages), (2) das Recovery-Ritual Sport in minimaler Form reaktivieren: eine 30-minütige moderate Trainingseinheit pro Woche reicht als erster Reset. Beide Maßnahmen kosten zusammen unter 30 Minuten täglich — und haben laut Meta-Analyse nach 4 Wochen messbare hormonelle Effekte."
    },
    "vo2max": {
      "score_context": "Dein VO2max Score von 50/100 entspricht einer geschätzten VO2max von 36.1 ml/kg/min — das ist das Fair-Band für einen 35-jährigen Mann. Du bist nicht auf dem Niveau eines Ausdauer-Athleten, aber auch nicht in einem Risikobereich. Es ist ein Startpunkt mit klarem Verbesserungspotenzial, besonders weil du aktuell 0 Vigorous-Aktivitäts-Minuten pro Woche hast.",
      "key_finding": "VO2max ist der stärkste einzelne Prädiktor für kardiovaskuläre Langzeitgesundheit und metabolische Effizienz. Bei 36.1 ml/kg/min bist du in einem Bereich, in dem jeder zusätzliche Punkt VO2max noch einen spürbaren Gewinn an Gesundheitsmargin bringt — oberhalb von ~45 ml/kg/min flacht diese Kurve ab. Gleichzeitig ist deine Schätzung direkt an dein Aktivitätslevel geknüpft: 0 intensive Trainingsminuten pro Woche erklären, warum du nicht im Good- oder Excellent-Band bist. Das ist die gute Nachricht: dieser Score ist stark veränderbar.",
      "fitness_context": "Im Fair-Band für 35-jährige Männer sind die Grundvorteile für kardiovaskuläre Gesundheit gegeben — du hast kein unmittelbares Risikoprofil. Der Abstand zum Good-Band (~42–46 ml/kg/min) ist realistisch schließbar: 8–12 Wochen progressive Intensitäts-Exposition würden diese Lücke signifikant verkleinern. Das würde sich auch direkt auf dein Energielevel im Alltag auswirken — höhere VO2max bedeutet, dass Alltagsbelastungen einen kleineren Anteil deiner Kapazität beanspruchen.",
      "estimation_note": "Diese VO2max von 36.1 ml/kg/min ist eine algorithmische Schätzung auf Basis der validierten Non-Exercise-Formel (Alter, BMI, Aktivitätskategorie, Geschlecht) — kein Laborwert und kein Ergebnis einer Spiroergometrie. Die Schätzung liefert eine robuste Einordnung für Performance-Insights und Trainingsplanung, aber für präzise Diagnose oder sportmedizinische Entscheidungen ist eine Labordiagnostik erforderlich.",
      "systemic_connection": "Deine geschätzte VO2max von 36.1 ml/kg/min ist das direkte Ergebnis deines Aktivitätsprofils — 0 intensive Einheiten, 813 MET-Minuten moderat. VO2max verbessert sich nicht durch Volumen allein, sondern durch Intensität: der Übergang von 0 auf 1 intensive Einheit pro Woche hätte den größten marginalen Effekt auf deinen geschätzten VO2max aller möglichen Maßnahmen. Gleichzeitig würde eine höhere VO2max deinen Recovery-Score positiv beeinflussen — kardiorespiratorische Fitness verbessert die Herzratenvariabilität, die im WHOOP-System direkt in den Recovery-Score einfließt.",
      "recommendation": "Beginne nach 4 Wochen Einstiegsphase (1× Kraft/Woche) mit dem Norwegian 4×4 Protokoll: 4 Minuten bei 90–95% der maximalen Herzfrequenz, 3 Minuten aktive Pause, 4 Wiederholungen — 1× pro Woche. Dieses Protokoll gehört zu den am besten untersuchten Interventionen für VO2max-Steigerung. Nach 8 Wochen konsistenter Durchführung ist eine Schätzungs-Verbesserung von 3–5 ml/kg/min realistisch — was dich in Richtung Good-Band bringen würde."
    }
  },
  "top_priority": "Dein Stress-Score von 30/100 bei einem Stresslevel von 7/10 ist der Hebel mit dem größten systemischen Einfluss — er drückt gleichzeitig deinen Schlaf (Sleep Multiplier ×0.87), deine Recovery (Score 38/100) und deine Körperkomposition (viszerale Fetteinlagerung, Insulinresistenz) nach unten. Kein anderes Modul hat diese drei simultanen Verbindungen. Die Maßnahme mit dem höchsten ROI für die nächsten 30 Tage: implementiere täglich 10 Minuten Box-Breathing (4-4-4-4) als festes Protokoll, platziert direkt nach dem letzten Arbeitstermin des Tages — der Zeitpunkt ist entscheidend, weil er den Übergang zwischen Job-Stressor und Familien-Zeit physisch markiert und Cortisol absenkt, bevor es sich in den Abend zieht. Parallel dazu: eine 30-minütige moderate Trainingseinheit pro Woche reaktivieren — Sport ist dein eigenes bevorzugtes Erholungsritual, und du nutzt es gerade nicht. Dieser Doppelhebel (Downregulation + minimale Sport-Reaktivierung) adressiert in 30 Tagen drei Module gleichzeitig: Stress, Recovery und Sleep. Der 30-Tage-Plan: Woche 1–2 nur die Atemroutine und eine Sport-Einheit einführen, keine anderen Änderungen; Woche 3–4 Schlaf-Cutoff-Zeit fixieren und Sitzpausen alle 45 Minuten einbauen. Vier Variablen, sequenziell eingeführt — das ist realistisch und adhärenzfähig.",
  "systemic_connections_overview": "Die wichtigste Verbindung in deinem Profil: dein Stresslevel von 7/10 sabotiert deinen Schlaf über den Stress-Multiplier (×0.87), und dein fragmentierter Schlaf von 6.5h mit häufigem Aufwachen verhindert vollständige Cortisol-Suppression in der Nacht — was deinen Stresslevel am nächsten Tag wieder erhöht. Das ist ein geschlossener Kreislauf, der deinen Recovery-Score strukturell bei 38/100 hält, obwohl du gar nicht trainierst. Die zweite kritische Verbindung: deine 9h Sitzzeit täglich ist ein unabhängiger kardiometabolischer Risikofaktor, der durch dein aktuelles Aktivitätsprofil (813 MET-Minuten moderat, 0 intensiv) nicht kompensiert wird — das Sitzzeit-Risiko existiert parallel zu deinem Bewegungspensum, nicht anstatt davon. Die dritte Verbindung: dein Kompositions-Ziel hängt direkt an Schlaf und Stress, nicht nur an Training und Ernährung — Covassin et al. (2022) zeigen, dass Schlafmangel viszerales Bauchfett unabhängig von der Ernährung erhöht, und erhöhtes Cortisol durch Stress begünstigt Fetteinlagerung direkt. Das bedeutet: du wirst Körperkomposition nicht verändern, solange Stress und Schlaf auf ihrem aktuellen Niveau bleiben — unabhängig davon, wie oft du trainierst oder was du isst.",
  "prognose_30_days": "Wenn du in den nächsten 30 Tagen konsequent täglich 10 Minuten Box-Breathing nach dem letzten Arbeitstermin durchführst, eine Trainingseinheit pro Woche reaktivierst und eine feste Aufwachzeit 7 Tage die Woche einhältst, ist eine messbare Verbesserung deines Erholungsgefühls von 5/10 auf 6–7/10 morgens realistisch. Dein über 7 Tage gemessener WHOOP Recovery-Score hat das Potenzial, von 38/100 auf 48–55/100 zu steigen — nicht durch Training, sondern durch die Reduktion der zwei aktiven Multiplikatoren (Stress und Schlaf). Die Körperkompositions-Veränderung in 30 Tagen wird noch minimal sein — das ist ein 90-Tage-Ziel; aber die hormonelle Basis (Cortisol sinkt, Testosteron erholt sich) für spätere Kompositionsveränderungen wird in diesem Monat gelegt.",
  "daily_life_protocol": {
    "morning": [
      {
        "habit": "Direkt nach dem Aufstehen: ein großes Glas Wasser (400–500 ml) trinken",
        "why_specific_to_user": "Du gibst an, nur 1.75 L Wasser täglich zu trinken — das Ziel sind 2.5 L. Dieser eine Trigger am Morgen deckt 20% des Tagesziels ohne Zeitaufwand und unterstützt die Cortisol-Kurve nach dem Aufwachen.",
        "time_cost_min": 0
      },
      {
        "habit": "5 Minuten natürliches Tageslicht nach dem Aufwachen — Fenster öffnen oder kurz nach draußen",
        "why_specific_to_user": "Dein Sleep Score von 60/100 mit häufigem nächtlichen Aufwachen deutet auf eine instabile Schlaf-Wach-Regulation hin. Morgendliches Licht setzt den circadianen Takt zurück und verbessert abendliche Melatonin-Ausschüttung — direkt relevant für deine Schlaf-Kontinuität.",
        "time_cost_min": 5
      },
      {
        "habit": "Erstes Frühstück innerhalb von 60 Minuten nach dem Aufstehen, mit mindestens 25–30g Protein",
        "why_specific_to_user": "Du hast das Ziel Körperfett reduzieren und Muskeln aufbauen — ein proteinreiches Frühstück innerhalb der ersten Stunde stabilisiert die Cortisol-Kurve am Morgen und reduziert abendliche Cravings, die du als Painpoint (cravings_evening) angibst.",
        "time_cost_min": 5
      }
    ],
    "work_day": [
      {
        "habit": "Sitzpause alle 45 Minuten: 2–3 Minuten aufstehen und tatsächlich gehen (nicht nur aufstehen)",
        "why_specific_to_user": "Deine Sitzzeit von 9h/Tag liegt im kritischen Bereich — AHA Science Advisory klassifiziert das als unabhängigen CVD-Risikofaktor. Diese Unterbrechung kostet 2–3 Minuten und ist der einzige Hebel, der das Sitzzeit-Risiko direkt adressiert.",
        "time_cost_min": 3
      },
      {
        "habit": "Nach dem letzten Arbeitstermin des Tages: 10 Minuten Box-Breathing (4 Sekunden ein, 4 halten, 4 aus, 4 halten) — BEVOR du in den Familien-Modus wechselst",
        "why_specific_to_user": "Du gibst Job und Familie als Hauptstressoren an. Dieser Übergangs-Ritual zwischen beiden Kontexten senkt Cortisol messbar (Psychoneuroendocrinology Meta-Analyse 2024) und verhindert, dass Arbeitsstress sich in den Abend zieht und deinen Schlaf (6.5h, Sleep Score 60/100) weiter fragmentiert.",
        "time_cost_min": 10
      },
      {
        "habit": "Koffein-Cutoff um 14:00 Uhr",
        "why_specific_to_user": "Häufiges nächtliches Aufwachen ist eines deiner Schlaf-Probleme. Koffein hat eine Halbwertszeit von 5–7 Stunden — Koffein nach 14:00 Uhr ist bei einem Schlafzeitpunkt vor 23:00 Uhr noch aktiv im System und erhöht die Schlaffragmentierung direkt.",
        "time_cost_min": 0
      }
    ],
    "evening": [
      {
        "habit": "60 Minuten vor dem Schlafen: Bildschirm-Cutoff (Smartphone, Laptop, TV) oder Blaulicht-Filter aktivieren",
        "why_specific_to_user": "Dein Sleep Score von 60/100 mit häufigem Aufwachen und einem Erholungsgefühl von 5/10 morgens braucht als erstes eine Verbesserung der Einschlaf-Qualität. Blaulicht hemmt Melatonin-Ausschüttung — dieser Cutoff ist der günstigste Einzel-Hebel für Schlafkontinuität.",
        "time_cost_min": 0
      },
      {
        "habit": "Schlafzimmer-Temperatur auf 16–19°C einstellen vor dem Schlafengehen",
        "why_specific_to_user": "Dein gemessener Recovery-Score von 38/100 (Sleep Multiplier ×0.82) braucht tiefere N3-Schlafphasen. Die thermoregulatorische Absenkung ist ein direkter Trigger für tieferen Schlaf — kostet null Minuten und verbessert die Schlafarchitektur ohne Verhaltensänderung.",
        "time_cost_min": 0
      },
      {
        "habit": "Abendessen mit mindestens 30g Protein, 2–3 Stunden vor dem Schlafen beenden",
        "why_specific_to_user": "Du gibst cravings_evening als Ernährungs-Painpoint an. Protein ist der stärkste Sättigungs-Makronährstoff — 30g Protein beim Abendessen stabilisiert den Blutzucker über die Nacht und reduziert abendliche Heißhunger-Episoden messbar.",
        "time_cost_min": 0
      }
    ],
    "nutrition_micro": [
      {
        "habit": "5-Minuten-Prep-Routine an einem fixen Tag pro Woche: 3 Portionen Protein-Quellen vorkochen (Eier, Hühnchenbrust, Hüttenkäse, Linsen)",
        "why_specific_to_user": "Du gibst no_time als Ernährungs-Painpoint an und hast ein Ziel Körperkomposition. Protein-Quellen verfügbar zu haben reduziert die Friction, die verhindert, dass du 25–30g pro Mahlzeit erreichst — ohne tägliche Planung.",
        "time_cost_min": 5
      },
      {
        "habit": "Glas Wasser vor jeder Mahlzeit (3× täglich = +600 ml Tageshydration)",
        "why_specific_to_user": "Du gibst 1.75 L Wasser täglich an — das Ziel für dein Körpergewicht und dein Aktivitätslevel wären 2.5 L. Dieser Trigger kostet keine Zeit, ist an eine bestehende Gewohnheit (Mahlzeiten) gebunden und schließt den Hydrations-Gap ohne zusätzliche Entscheidungsenergie.",
        "time_cost_min": 0
      }
    ],
    "total_time_min_per_day": 28
  },
  "disclaimer": "Alle Angaben sind modellbasierte Performance-Insights auf Basis selbstberichteter Daten. Kein Ersatz für medizinische Diagnostik. VO2max ist eine algorithmische Schätzung — keine Labormessung.",
  "executive_findings": [
    {
      "type": "weakness",
      "headline": "Bewegungsmangel sabotiert dein Körperkompositions-Ziel",
      "body": "Mit \"0 days/wk\" strukturierter Aktivität und \"9h sitting\" täglich fehlt dir die Grundlage für Muskelaufbau. Dein Activity-Score von 43 zeigt, dass alltägliche Bewegung nicht ausreicht. Nutze dein Lieblings-Recovery-Ritual Sport gezielt ein.",
      "related_dimension": "activity"
    },
    {
      "type": "strength",
      "headline": "Stress-Management schafft Basis für Erfolg",
      "body": "Dein Stress-Score von 30 ist relativ niedrig trotz Job- und Familiendruck (7/10). Das zeigt Widerstandskraft. Diese Stabilität kannst du nutzen, um konsequent an deinem Body-Composition-Plan zu arbeiten.",
      "related_dimension": "stress"
    },
    {
      "type": "connection",
      "headline": "Schlafqualität und Abendcravings sind verbunden",
      "body": "Du schläfst nur 6.5h mit \"wakeups oft\" und schlechter Qualität (mittel). Das destabilisiert deinen Appetithaushalt und verschärft deine \"cravings_evening\". Ein konsistenterer Schlaf-Rhythmus mit Screen-Cutoff würde beides verbessern.",
      "related_dimension": "sleep"
    }
  ],
  "cross_insights": [
    {
      "dimension_a": "sleep",
      "dimension_b": "stress",
      "headline": "Dein Schlaf wird durch Job und Familie belastet",
      "body": "Mit \"7/10\" Stress und nur \"6.5h\" Schlaf pro Nacht verschärfst du einen Teufelskreis. Deine \"oft\" Wakeups deuten auf stressbedingte Schlaffragmentierung hin. Priorisiere einen Screen-Cutoff 90min vor dem Schlafengehen, um Cortisol zu senken und deine Erholung von \"5/10\" zu verbessern."
    },
    {
      "dimension_a": "activity",
      "dimension_b": "metabolic",
      "headline": "Deine Sitzdauer sabotiert dein Körperkompositions-Ziel",
      "body": "\"0 Tage/Woche\" strukturierte Aktivität plus \"9h Sitzen\" täglich bremsen deinen Metabolismus (57). Dein Body-Comp-Goal erfordert mindestens 3x/Woche moderate Bewegung. Nutze dein Lieblings-Recovery-Ritual (Sport) als Ankerpunkt—statt \"0 steps/day\" könnten regelmäßige Sessions deinen VO2max (50) deutlich heben."
    },
    {
      "dimension_a": "nutrition",
      "dimension_b": "stress",
      "headline": "Deine Abend-Cravings werden durch Zeit und Stress getriggert",
      "body": "Bei \"7/10\" Stress und \"no_time\" als Ernährungs-Pain-Point greifen deine \"cravings_evening\" um Cortisol zu regulieren. Mit nur \"1.75L Wasser\" und \"eher selten\" Obst/Gemüse fehldir Nährstoffdichte. Präpariere 2x/Woche Snack-Boxen (Nüsse, Obst) als stressresistente Alternative."
    }
  ]
},
};

const SCORES: Record<string, PdfScores> = {
  de: {
  "sleep": {
    "score": 60,
    "band": "moderate"
  },
  "recovery": {
    "score": 38,
    "band": "low"
  },
  "activity": {
    "score": 43,
    "band": "moderate"
  },
  "metabolic": {
    "score": 57,
    "band": "moderate"
  },
  "stress": {
    "score": 30,
    "band": "high"
  },
  "vo2max": {
    "score": 50,
    "band": "Fair",
    "estimated": 36.1
  },
  "overall": {
    "score": 50,
    "band": "moderate"
  },
  "total_met": 813,
  "sleep_duration_hours": 6.6,
  "sitting_hours": 9,
  "training_days": 2
},
};

export function getSamplePdfContent(locale: string): PdfReportContent {
  return CONTENT[locale] ?? CONTENT.de;
}
export function getSamplePdfScores(locale: string): PdfScores {
  return SCORES[locale] ?? SCORES.de;
}
