// AUTO-GENERATED by scripts/convert-sample-data.mjs — do not edit by hand.
// Source: sample-data/raw/<locale>.json (real /api/master-plan/generate output).
import type { MasterPlan } from "@/lib/master-plan/schema";

const MASTER: Record<string, MasterPlan> = {
  de: {
  "title": "MASTER-WOCHENPLAN",
  "subtitle": "Personalisiert für dich, zugeschnitten auf deine Ziele",
  "color": "#E63222",
  "score": 50,
  "intro": "Dein Plan kombiniert Körperkomposition (Muskelaufbau & Fettabbau) mit deinem aktuellen Stresslevel aus Job und Familie. Wegen des hohen Stresses bleiben wir bei maximal 3 Trainingstagen und halten die Intensität bewusst niedrig — das schützt Cortisol (Stresshormon) und fördert trotzdem Körperzusammensetzung. Ernährung und Recovery sind diese Woche genauso wichtig wie das Training selbst.",
  "rows": [
    {
      "day": "mon",
      "training": [
        "Bodyweight-Kraft: 3×10 Kniebeugen + 3×8 Push-ups + 3×10 Ausfallschritte · RPE 5 (Belastung 5/10, moderat) · 30 Min"
      ],
      "nutrition": [
        "Abend-Craving-Stopper: 20g Whey-Protein + 1 EL Erdnussbutter direkt nach dem Training — Protein sättigt und reduziert Insulin-Schwankungen"
      ],
      "recovery": [
        "Legs-Up-the-Wall: 5 Min Beine an der Wand — aktiviert parasympathisches Nervensystem, senkt Herzfrequenz"
      ],
      "stress_anchor": [
        "Physiological Sigh: 2× kurz einatmen, 1× lang ausatmen, 4 Wdh. — senkt akuten Stress in unter 90 Sek (Huberman Lab)"
      ]
    },
    {
      "day": "tue",
      "training": [
        "PAUSE"
      ],
      "nutrition": [
        "Schnelles Mittag: 150g Hähnchen + 200g Süßkartoffel + Brokkoli vorgekocht (32g Protein) — Meal-Prep spart Zeit und verhindert Abend-Cravings"
      ],
      "recovery": [
        "Cold-Face-Splash: 30 Sek kaltes Wasser ins Gesicht — Mammalian Dive Reflex, senkt Herzfrequenz schnell"
      ],
      "stress_anchor": [
        "NSDR-Audio (Non-Sleep Deep Rest — kommt der Schlaf-Erholung am nächsten): 15 Min Pause, z.B. Reveri-App"
      ]
    },
    {
      "day": "wed",
      "training": [
        "Cardio-Walking Z2 (Zone 2 — Tempo bei dem du noch sprechen kannst): 40 Min flottes Gehen · RPE 4 (Belastung 4/10, locker)"
      ],
      "nutrition": [
        "Protein-First-Regel: Jede Mahlzeit startet mit der Proteinquelle (Ei, Quark, Fleisch) — reduziert Gesamt-Kalorienaufnahme ohne Zählen"
      ],
      "recovery": [
        "Contrast Shower: 3× wechseln zwischen 1 Min warm und 30 Sek kalt — verbessert HRV (Herzfrequenzvariabilität — Anzeichen wie erholt dein Körper ist)"
      ],
      "stress_anchor": [
        "5-4-3-2-1 Grounding: 5 Dinge sehen, 4 hören, 3 fühlen — unterbricht Cortisol (Stresshormon)-Spirale nach Arbeitstag"
      ]
    },
    {
      "day": "thu",
      "training": [
        "PAUSE"
      ],
      "nutrition": [
        "Abend-Craving-Protokoll: 200g griechischer Joghurt (0%) + Beeren + 1 TL Honig — hohe Sättigung, niedrige Kaloriendichte, stabilisiert Blutzucker"
      ],
      "recovery": [
        "Progressive Muskelentspannung nach Jacobson: 10 Min — Muskeln anspannen und loslassen von Fuß bis Kopf, senkt Cortisol (Stresshormon) messbar"
      ],
      "stress_anchor": [
        "Coffee Nap: Espresso trinken, dann 20 Min Nap — Adenosin-Clearance maximiert Erholungseffekt"
      ]
    },
    {
      "day": "fri",
      "training": [
        "Bodyweight-Kraft: 3×12 Dips (Stuhl) + 3×10 Rudern (Tisch) + 3×15 Glute Bridges · RPE 5 (Belastung 5/10, moderat) · 30 Min"
      ],
      "nutrition": [
        "Pre-Workout: 1 Banane + 20g Whey 30 Min vorher — schnelle Kohlenhydrate + Protein für Muskelproteinsynthese ohne Magen-Stress"
      ],
      "recovery": [
        "Foam Rolling: 5 Min Oberschenkel + Waden — mechanische Kompression erhöht lokale Durchblutung und reduziert Muskelkater"
      ],
      "stress_anchor": [
        "Physiological Sigh: 2× kurz einatmen, 1× lang ausatmen, 4 Wdh. — senkt akuten Stress in unter 90 Sek (Huberman Lab)"
      ]
    },
    {
      "day": "sat",
      "training": [
        "PAUSE"
      ],
      "nutrition": [
        "Wochenend-Meal-Prep: 500g Hühnerbrust + Reis + Gemüse für 3 Tage vorkochen — NEAT (Alltagsbewegung außerhalb vom Training) durch Küchenstehen erhöht Kalorienverbrauch"
      ],
      "recovery": [
        "NSDR-Audio (Non-Sleep Deep Rest — kommt der Schlaf-Erholung am nächsten): 20 Min am Nachmittag — regeneriert Dopamin-Baseline"
      ],
      "stress_anchor": [
        "Soziale Erholung: 30 Min bewusste Zeit mit Familie ohne Bildschirm — Oxytocin-Ausschüttung senkt Allostatic Load (kumulative Stressbelastung über Zeit)"
      ]
    },
    {
      "day": "sun",
      "training": [
        "PAUSE"
      ],
      "nutrition": [
        "Deficit (Kalorien-Minus unter deinem Tagesbedarf) an Ruhetagen: Mahlzeiten um ~200 kcal reduzieren durch kleinere Kohlenhydrat-Portion — unterstützt Fettabbau ohne Muskelverlust"
      ],
      "recovery": [
        "Legs-Up-the-Wall: 5 Min + bewusstes Scannen des Körpers von Kopf bis Fuß — parasympathische Aktivierung für die Woche danach"
      ],
      "stress_anchor": [
        "Wochenplanung: 10 Min Sonntag-Abend die 3 wichtigsten Aufgaben für Montag notieren — reduziert antizipatorisches Cortisol (Stresshormon) am Morgen"
      ]
    }
  ]
},
};

export function getSampleMasterPlan(locale: string): MasterPlan {
  return MASTER[locale] ?? MASTER.de;
}
