// Plan PDFs are produced exclusively from the AI-personalised content
// generated by /api/plan/generate and uploaded by the frontend in
// `prepare-pdfs`. There is no server-side reconstruction path: regenerating
// from raw scores would produce a deterministic, non-personalised plan
// that overwrites the AI output. If a plan PDF is missing in Storage, the
// caller must either retry plan generation or render on-demand via
// `/api/plan/pdf` — this route always returns 404.

import { NextRequest, NextResponse } from "next/server";
import { upsertStatus, type PdfType } from "@/lib/pdf/status";
import type { Locale } from "@/lib/supabase/types";

export const runtime = "nodejs";
export const maxDuration = 30;

export async function POST(req: NextRequest) {
  let assessmentId = "";
  let pdfType: PdfType = "plan_activity";
  let locale: Locale = "de";

  try {
    const body = await req.json() as {
      assessment_id: string;
      pdf_type: PdfType;
      locale: string;
    };
    assessmentId = body.assessment_id;
    pdfType = body.pdf_type;
    locale = (body.locale ?? "de") as Locale;

    if (!assessmentId || !pdfType || pdfType === "main_report") {
      return NextResponse.json({ error: "Invalid params" }, { status: 400 });
    }

    await upsertStatus(assessmentId, pdfType, locale, "failed").catch(() => {});

    return NextResponse.json(
      { error: "plan_pdf_not_available", message: "Plan PDF must be generated and uploaded by the client; on-demand reconstruction is disabled." },
      { status: 404 },
    );
  } catch (err) {
    console.error("[generate-single-pdf] error:", err);
    if (assessmentId && pdfType) {
      await upsertStatus(assessmentId, pdfType, locale, "failed").catch(() => {});
    }
    return NextResponse.json({ error: "Generation failed" }, { status: 500 });
  }
}
