import type { Locale } from "@/lib/supabase/types";

// Operational Glossar für Plan-PDFs v2.
// Tone-Regel: Erklärungen beschreiben was der USER konkret TUT oder SPÜRT —
// nicht was der Begriff wissenschaftlich bedeutet. "Norwegian 4×4 Protocol"
// → "4× schnell laufen für 4 Min, dann 3 Min Pause, das ganze 4 mal", NICHT
// → "VO2max-optimiertes hochintensives Intervalltraining".

export const PLAN_GLOSSARY: Record<Locale, Record<string, string>> = {
  de: {
    "VO2max": "deine maximale Sauerstoffaufnahme — zeigt wie fit dein Herz-Kreislauf-System ist",
    "Z2": "Zone 2 — Tempo bei dem du noch sprechen kannst",
    "Zone 2": "Tempo bei dem du noch sprechen kannst",
    "Z3": "Zone 3 — moderates Tempo, du kannst nur noch kurze Sätze sagen",
    "Zone 3": "moderates Tempo, du kannst nur noch kurze Sätze sagen",
    "Z4": "Zone 4 — hartes Tempo, du kannst nur einzelne Wörter sagen",
    "Zone 4": "hartes Tempo, du kannst nur einzelne Wörter sagen",
    "Z5": "Zone 5 — maximaler Bereich, all-out, du kannst nicht mehr sprechen",
    "Zone 5": "maximaler Bereich, all-out, du kannst nicht mehr sprechen",
    "HRmax": "deine maximale Herzfrequenz",
    "85-90% HRmax": "so schnell dass du kaum noch reden kannst",
    "HRV": "Herzfrequenzvariabilität — Anzeichen wie erholt dein Körper ist",
    "MET 8.0": "intensive Belastung wie Joggen",
    "MET-min": "Maß für deinen Trainingsumfang — Stunden mal Intensität",
    "Norwegian 4×4 Protocol": "4× schnell laufen für 4 Min, dann 3 Min Pause, das ganze 4 mal",
    "EMOM": "Every Minute On the Minute — pro Minute eine festgelegte Übungsrunde",
    "AMRAP": "As Many Reps As Possible — möglichst viele Wiederholungen in fester Zeit",
    "RPE": "wie anstrengend es sich anfühlt auf einer Skala 1-10",
    "Tempo-Lauf": "schnelles aber kontrolliertes Lauftempo — du kannst nur noch wenige Wörter sagen",
    "Long Run": "der längste Lauf der Woche — gemütliches Tempo",
    "Mobility": "Beweglichkeitsübungen für Gelenke und Muskeln",
    "Cortisol": "Stresshormon — morgens am höchsten, abends sollte es niedrig sein",
    "Allostatic Load": "kumulative Stressbelastung über Zeit",
    "Surplus": "Kalorien-Plus über deinem Tagesbedarf",
    "Deficit": "Kalorien-Minus unter deinem Tagesbedarf",
    "Makros": "Makronährstoffe — Protein, Fett, Kohlenhydrate",
    "NEAT": "Alltagsbewegung außerhalb vom Training — Treppen, Laufen, Stehen",
  },
  en: {
    "VO2max": "your maximum oxygen uptake — shows how fit your heart and lungs are",
    "Z2": "Zone 2 — pace where you can still hold a conversation",
    "Zone 2": "pace where you can still hold a conversation",
    "Z3": "Zone 3 — moderate pace, you can only say short sentences",
    "Zone 3": "moderate pace, you can only say short sentences",
    "Z4": "Zone 4 — hard pace, you can only say single words",
    "Zone 4": "hard pace, you can only say single words",
    "Z5": "Zone 5 — maximum zone, all-out, you can't talk anymore",
    "Zone 5": "maximum zone, all-out, you can't talk anymore",
    "HRmax": "your maximum heart rate",
    "85-90% HRmax": "so fast you can barely talk",
    "HRV": "heart rate variability — a sign of how recovered your body is",
    "MET 8.0": "intense effort like jogging",
    "MET-min": "your training volume — hours times intensity",
    "Norwegian 4×4 Protocol": "run fast for 4 min, then 3 min easy, repeat 4 times",
    "EMOM": "Every Minute On the Minute — one round of an exercise per minute",
    "AMRAP": "As Many Reps As Possible — fit as many reps into a fixed time as you can",
    "RPE": "how hard it feels on a 1-10 scale",
    "Tempo Run": "fast but controlled pace — you can only say a few words",
    "Long Run": "longest run of the week — easy pace",
    "Mobility": "joint and muscle flexibility exercises",
    "Cortisol": "stress hormone — highest in the morning, should be low at night",
    "Allostatic Load": "cumulative stress load over time",
    "Surplus": "calorie intake above your daily need",
    "Deficit": "calorie intake below your daily need",
    "Macros": "macronutrients — protein, fat, carbs",
    "NEAT": "daily movement outside training — stairs, walking, standing",
  },
  it: {
    "VO2max": "il tuo consumo massimo di ossigeno — mostra quanto sono in forma cuore e polmoni",
    "Z2": "Zona 2 — ritmo a cui riesci ancora a parlare",
    "Zone 2": "ritmo a cui riesci ancora a parlare",
    "Z3": "Zona 3 — ritmo moderato, riesci a dire solo frasi brevi",
    "Zone 3": "ritmo moderato, riesci a dire solo frasi brevi",
    "Z4": "Zona 4 — ritmo duro, riesci a dire solo singole parole",
    "Zone 4": "ritmo duro, riesci a dire solo singole parole",
    "Z5": "Zona 5 — massimo sforzo, all-out, non riesci più a parlare",
    "Zone 5": "massimo sforzo, all-out, non riesci più a parlare",
    "HRmax": "la tua frequenza cardiaca massima",
    "85-90% HRmax": "così veloce che a malapena riesci a parlare",
    "HRV": "variabilità della frequenza cardiaca — segnale di quanto sei recuperato",
    "MET 8.0": "sforzo intenso come fare jogging",
    "MET-min": "il tuo volume di allenamento — ore per intensità",
    "Norwegian 4×4 Protocol": "corri veloce per 4 min, poi 3 min facili, ripeti 4 volte",
    "EMOM": "Every Minute On the Minute — un round di esercizi al minuto",
    "AMRAP": "As Many Reps As Possible — quante più ripetizioni in un tempo fisso",
    "RPE": "quanto ti sembra duro su una scala da 1 a 10",
    "Tempo Run": "ritmo veloce ma controllato — riesci a dire solo poche parole",
    "Long Run": "la corsa più lunga della settimana — ritmo facile",
    "Mobility": "esercizi di mobilità per articolazioni e muscoli",
    "Cortisol": "ormone dello stress — più alto al mattino, dovrebbe essere basso la sera",
    "Allostatic Load": "carico cumulativo di stress nel tempo",
    "Surplus": "calorie in più rispetto al tuo fabbisogno giornaliero",
    "Deficit": "calorie in meno rispetto al tuo fabbisogno giornaliero",
    "Macros": "macronutrienti — proteine, grassi, carboidrati",
    "NEAT": "movimento quotidiano fuori dall'allenamento — scale, camminare, stare in piedi",
  },
  tr: {
    "VO2max": "maksimum oksijen alımın — kalp ve akciğerlerinin ne kadar fit olduğunu gösterir",
    "Z2": "Zone 2 — hâlâ konuşabildiğin tempo",
    "Zone 2": "hâlâ konuşabildiğin tempo",
    "Z3": "Zone 3 — orta tempo, sadece kısa cümleler söyleyebilirsin",
    "Zone 3": "orta tempo, sadece kısa cümleler söyleyebilirsin",
    "Z4": "Zone 4 — sert tempo, sadece tek kelimeler söyleyebilirsin",
    "Zone 4": "sert tempo, sadece tek kelimeler söyleyebilirsin",
    "Z5": "Zone 5 — maksimum bölge, all-out, artık konuşamazsın",
    "Zone 5": "maksimum bölge, all-out, artık konuşamazsın",
    "HRmax": "maksimum kalp atış hızın",
    "85-90% HRmax": "neredeyse konuşamayacağın kadar hızlı",
    "HRV": "kalp atış hızı değişkenliği — vücudunun ne kadar toparlandığının göstergesi",
    "MET 8.0": "koşu gibi yoğun efor",
    "MET-min": "antrenman hacmin — saat çarpı yoğunluk",
    "Norwegian 4×4 Protocol": "4 dk hızlı koş, sonra 3 dk yavaş, 4 kez tekrarla",
    "EMOM": "Every Minute On the Minute — dakika başına bir egzersiz turu",
    "AMRAP": "As Many Reps As Possible — sabit sürede mümkün olduğunca çok tekrar",
    "RPE": "ne kadar zor hissettirdiği 1-10 skalasında",
    "Tempo Run": "hızlı ama kontrollü tempo — sadece birkaç kelime söyleyebilirsin",
    "Long Run": "haftanın en uzun koşusu — kolay tempo",
    "Mobility": "eklem ve kas esneklik egzersizleri",
    "Cortisol": "stres hormonu — sabah en yüksek, akşam düşük olmalı",
    "Allostatic Load": "zaman içinde biriken stres yükü",
    "Surplus": "günlük ihtiyacının üzerinde kalori alımı",
    "Deficit": "günlük ihtiyacının altında kalori alımı",
    "Macros": "makro besinler — protein, yağ, karbonhidrat",
    "NEAT": "antrenman dışı günlük hareket — merdiven, yürüme, ayakta durma",
  },
};

// Locale-spezifischer "z.B."-Marker (für Validation + Re-Generation-Prompts).
export const EXAMPLE_MARKER: Record<Locale, string> = {
  de: "z.B.",
  en: "e.g.",
  it: "ad es.",
  tr: "örn.",
};

// Pause-Erkennung in der Tag-Tabelle (Pause-Rows sind vom z.B.-Mandate ausgenommen).
export const PAUSE_PATTERN: Record<Locale, RegExp> = {
  de: /^\s*(pause|rest)\b/i,
  en: /^\s*(rest|pause|off)\b/i,
  it: /^\s*(pausa|riposo|rest)\b/i,
  tr: /^\s*(dinlenme|pause|rest)\b/i,
};
